"""create word_translations table

Revision ID: 0352dbd4b87a
Revises: a42134af1cef
Create Date: 2026-06-16 15:39:04.606175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0352dbd4b87a'
down_revision: Union[str, Sequence[str], None] = 'a42134af1cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_word_id', sa.UUID(), nullable=False),
    sa.Column('language_id', sa.UUID(), nullable=False),
    sa.Column('translation', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['base_word_id'], ['base_words.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_translations')
    # ### end Alembic commands ###
