"""create sentences table

Revision ID: 13b348cf011b
Revises: d4720fb1a9e2
Create Date: 2026-06-11 18:18:40.506662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13b348cf011b'
down_revision: Union[str, Sequence[str], None] = 'd4720fb1a9e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('language_id', sa.UUID(), nullable=False),
    sa.Column('word_category_id', sa.UUID(), nullable=False),
    sa.Column('grammar_rule_id', sa.UUID(), nullable=False),
    sa.Column('row_position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grammar_rule_id'], ['grammar_rules.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['word_category_id'], ['word_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentences')
    # ### end Alembic commands ###
