"""create word_rule_assignments table

Revision ID: 21296331448a
Revises: c6fd174f15b4
Create Date: 2026-06-16 16:19:51.794857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21296331448a'
down_revision: Union[str, Sequence[str], None] = 'c6fd174f15b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_rule_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_word_id', sa.UUID(), nullable=False),
    sa.Column('grammar_rule_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['base_word_id'], ['base_words.id'], ),
    sa.ForeignKeyConstraint(['grammar_rule_id'], ['grammar_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_rule_assignments')
    # ### end Alembic commands ###
