"""create word_form_sentences table

Revision ID: 40ab3af1be2b
Revises: 87cb7f7b76e6
Create Date: 2026-06-16 16:45:23.932412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40ab3af1be2b'
down_revision: Union[str, Sequence[str], None] = '87cb7f7b76e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_form_sentences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('word_form_id', sa.UUID(), nullable=False),
    sa.Column('sentence_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.ForeignKeyConstraint(['word_form_id'], ['word_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_form_sentences')
    # ### end Alembic commands ###
