"""create word_forms table

Revision ID: 5039fca297bf
Revises: f421be47a080
Create Date: 2026-06-16 16:36:59.855931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5039fca297bf'
down_revision: Union[str, Sequence[str], None] = 'f421be47a080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_forms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('word_rule_assignment_id', sa.UUID(), nullable=False),
    sa.Column('grammar_rule_row_id', sa.UUID(), nullable=False),
    sa.Column('form', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['grammar_rule_row_id'], ['grammar_rule_rows.id'], ),
    sa.ForeignKeyConstraint(['word_rule_assignment_id'], ['word_rule_assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_forms')
    # ### end Alembic commands ###
