"""create expression_translations table

Revision ID: 69ddecfe8fd3
Revises: 13b348cf011b
Create Date: 2026-06-15 16:21:33.416481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69ddecfe8fd3'
down_revision: Union[str, Sequence[str], None] = '13b348cf011b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expression_translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expression_id', sa.UUID(), nullable=False),
    sa.Column('language_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['expression_id'], ['expressions.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expression_translations')
    # ### end Alembic commands ###
