"""create word_form_translations table

Revision ID: 87cb7f7b76e6
Revises: 5039fca297bf
Create Date: 2026-06-16 16:42:38.753524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87cb7f7b76e6'
down_revision: Union[str, Sequence[str], None] = '5039fca297bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_form_translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('word_form_id', sa.UUID(), nullable=False),
    sa.Column('language_id', sa.UUID(), nullable=False),
    sa.Column('translation', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['word_form_id'], ['word_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_form_translations')
    # ### end Alembic commands ###
