"""create grammar_rule_rows table

Revision ID: 891da455278d
Revises: 21296331448a
Create Date: 2026-06-16 16:23:42.065284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '891da455278d'
down_revision: Union[str, Sequence[str], None] = '21296331448a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_rule_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grammar_rule_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grammar_rule_id'], ['grammar_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grammar_rule_rows')
    # ### end Alembic commands ###
