"""add unique constraint on chat_messages session_id position

Revision ID: abdffbb1c3f9
Revises: b03a14072dea
Create Date: 2026-09-10 13:16:24.036977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abdffbb1c3f9'
down_revision: Union[str, Sequence[str], None] = 'b03a14072dea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_chat_messages_session_position', 'chat_messages', ['session_id', 'position'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chat_messages_session_position', 'chat_messages', type_='unique')
    # ### end Alembic commands ###
