"""create base_words table

Revision ID: c44a2a0c6b71
Revises: 2ccc12f7e23b
Create Date: 2026-06-11 18:10:39.095084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c44a2a0c6b71'
down_revision: Union[str, Sequence[str], None] = '2ccc12f7e23b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_words',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('language_id', sa.UUID(), nullable=False),
    sa.Column('word_category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['word_category_id'], ['word_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('base_words')
    # ### end Alembic commands ###
