"""create grammar_rule_translations table

Revision ID: c6fd174f15b4
Revises: 0352dbd4b87a
Create Date: 2026-06-16 16:02:02.588798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6fd174f15b4'
down_revision: Union[str, Sequence[str], None] = '0352dbd4b87a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_rule_translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grammar_rule_id', sa.UUID(), nullable=False),
    sa.Column('language_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['grammar_rule_id'], ['grammar_rules.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grammar_rule_translations')
    # ### end Alembic commands ###
