"""create grammar_rules table

Revision ID: d4720fb1a9e2
Revises: c44a2a0c6b71
Create Date: 2026-06-11 18:13:51.043671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4720fb1a9e2'
down_revision: Union[str, Sequence[str], None] = 'c44a2a0c6b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language_id', sa.UUID(), nullable=False),
    sa.Column('word_category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['word_category_id'], ['word_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grammar_rules')
    # ### end Alembic commands ###
