"""create language_pairs table

Revision ID: eb4d837ee312
Revises: 40ab3af1be2b
Create Date: 2026-06-25 15:54:58.791795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb4d837ee312'
down_revision: Union[str, Sequence[str], None] = '40ab3af1be2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_pairs',
    sa.Column('pair_id', sa.UUID(), nullable=False),
    sa.Column('native_language_id', sa.UUID(), nullable=False),
    sa.Column('target_language_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['native_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['target_language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('pair_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('language_pairs')
    # ### end Alembic commands ###
