"""create grammar_rule_row_translations table

Revision ID: f421be47a080
Revises: 891da455278d
Create Date: 2026-06-16 16:33:53.327759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f421be47a080'
down_revision: Union[str, Sequence[str], None] = '891da455278d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_rule_row_translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grammar_rule_row_id', sa.UUID(), nullable=False),
    sa.Column('language_id', sa.UUID(), nullable=False),
    sa.Column('label_translation', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['grammar_rule_row_id'], ['grammar_rule_rows.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grammar_rule_row_translations')
    # ### end Alembic commands ###
